# Based off the script from the react-native-firebase project. Licenced under the Apache 2.0 licence
# Details: https://github.com/invertase/react-native-firebase

# -------------------------
#        DEFAULTS
# -------------------------
defaults: &defaults
  working_directory: ~/react-native-netinfo
  environment:
  - GIT_COMMIT_DESC: git log --format=oneline -n 1 $CIRCLE_SHA1

# JAVASCRIPT
js_defaults: &js_defaults
  <<: *defaults
  docker:
  - image: circleci/node:8
  environment:
  - PATH: "/opt/yarn/yarn-v1.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# ANDROID
android_defaults: &android_defaults
  <<: *defaults
  docker:
  - image: circleci/android:api-27-node8-alpha
  resource_class: "large"
  environment:
  - TERM: "dumb"
  - ADB_INSTALL_TIMEOUT: 10
  - _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
  - GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+HeapDumpOnOutOfMemoryError"'
  - BUILD_THREADS: 2

# -------------------------
#         ALIASES
# -------------------------

aliases:
# CACHE
- &restore-yarn-cache
  keys:
  - yarn-cache-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
  - yarn-cache-{{ arch }}
- &save-yarn-cache
  paths:
  - ~/.cache/yarn
  - ~/Library/Detox/ios
  key: yarn-cache-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

- &restore-gradle-cache
  keys:
  - gradle-cache-{{ checksum "android/build.gradle" }}-{{ checksum "example/android/build.gradle" }}-{{ checksum "example/android/app/build.gradle" }}
- &save-gradle-cache
  paths:
  - ~/.gradle
  key: gradle-cache-{{ checksum "android/build.gradle" }}-{{ checksum "example/android/build.gradle" }}-{{ checksum "example/android/app/build.gradle" }}

# INSTALLATION
- &yarn
  name: Yarn Install
  command: |
    yarn install --network-concurrency 1 --non-interactive --cache-folder ~/.cache/yarn & wait

# ANALYSE
- &flow
  name: Flow Checks
  command: yarn ci:test:flow

- &javascript
  name: Javascript Tests
  command: yarn ci:test:js

# -------------------------
#          JOBS
# -------------------------
version: 2
jobs:
  # Set up a Node environment for downstream jobs
  checkout-code:
    <<: *js_defaults
    steps:
    - checkout
    - restore-cache: *restore-yarn-cache
    - run: rm -rf node_modules
    - run: yarn cache clean
    - run: *yarn
    - save-cache: *save-yarn-cache
    - persist_to_workspace:
        root: .
        paths: .

  flow:
    <<: *js_defaults
    steps:
    - attach_workspace:
        at: ~/react-native-netinfo
    - run: *flow
  
  javascript:
    <<: *js_defaults
    steps:
    - attach_workspace:
        at: ~/react-native-netinfo
    - run: *javascript
  
  android-compile:
    <<: *android_defaults
    steps:
    - attach_workspace:
        at: ~/react-native-netinfo
    - restore-cache: *restore-gradle-cache
    - run:
        name: Accept Android licences
        command: |-
          yes | sdkmanager --licenses || exit 0
          yes | sdkmanager --update || exit 0
    - run:
        name: Build Android Example App and Library
        command: |-
          cd example/android
          ./gradlew clean assembleDebug
    - save-cache: *save-gradle-cache


# -------------------------
#        WORKFLOWS
# -------------------------
workflows:
  version: 2
  Test:
    jobs:
    - checkout-code
    - flow:
        requires:
        - checkout-code
    - javascript:
        requires:
        - checkout-code
    - android-compile:
        requires:
        - checkout-code
